CREATE TABLE IF NOT EXISTS orders (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    
    -- From CSV
    latitude DECIMAL(10, 7) NOT NULL,
    longitude DECIMAL(10, 7) NOT NULL,
    subtotal NUMERIC(12, 2) NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    
    -- Calculated Tax Fields
    composite_tax_rate NUMERIC(6, 5) NOT NULL,
    tax_amount NUMERIC(12, 2) NOT NULL,
    total_amount NUMERIC(12, 2) NOT NULL,
    
    -- Breakdown and Jurisdictions
    breakdown JSONB NOT NULL,
    jurisdictions JSONB NOT NULL,
    
    -- Audit trail
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER SEQUENCE orders_id_seq RESTART WITH 100000;

CREATE INDEX idx_orders_timestamp ON orders(timestamp);
CREATE INDEX idx_orders_tax_amount ON orders(tax_amount);
CREATE INDEX idx_orders_pagination ON orders(id);
CREATE INDEX idx_orders_location ON orders (latitude, longitude);